---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green-deployment
  labels:
    type: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      type: proxy
  template:
    metadata:
      name: nginx-pod
      labels:
        type: proxy
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
...





