---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  labels:
    type: appserver
spec:
  containers:
    - name: mytomcat
      image: tomee
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: slave1
                operator: In
                values:
                  - intelliqit1
...
