---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    author: intelliqit
    type: db
spec:
  containers:
    - name: mydb
      image: mysql:5
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: intelliiqt
...
